<?php

namespace App\Helpers;

class KotaIndonesia
{
    public static function list(): array
    {
        return [
            // ── JAWA TIMUR ──
            'Surabaya'          => 'Surabaya',
            'Malang'            => 'Malang',
            'Kab. Malang'       => 'Kab. Malang',
            'Batu'              => 'Batu',
            'Sidoarjo'          => 'Sidoarjo',
            'Gresik'            => 'Gresik',
            'Mojokerto'         => 'Mojokerto',
            'Jombang'           => 'Jombang',
            'Pasuruan'          => 'Pasuruan',
            'Probolinggo'       => 'Probolinggo',
            'Lumajang'          => 'Lumajang',
            'Jember'            => 'Jember',
            'Banyuwangi'        => 'Banyuwangi',
            'Situbondo'         => 'Situbondo',
            'Bondowoso'         => 'Bondowoso',
            'Kediri'            => 'Kediri',
            'Blitar'            => 'Blitar',
            'Tulungagung'       => 'Tulungagung',
            'Trenggalek'        => 'Trenggalek',
            'Nganjuk'           => 'Nganjuk',
            'Madiun'            => 'Madiun',
            'Magetan'           => 'Magetan',
            'Ngawi'             => 'Ngawi',
            'Bojonegoro'        => 'Bojonegoro',
            'Tuban'             => 'Tuban',
            'Lamongan'          => 'Lamongan',
            'Bangkalan'         => 'Bangkalan',
            'Sampang'           => 'Sampang',
            'Pamekasan'         => 'Pamekasan',
            'Sumenep'           => 'Sumenep',
            'Pacitan'           => 'Pacitan',
            'Ponorogo'          => 'Ponorogo',

            // ── JAWA TENGAH ──
            'Semarang'          => 'Semarang',
            'Solo'              => 'Solo',
            'Yogyakarta'        => 'Yogyakarta',
            'Sleman'            => 'Sleman',
            'Bantul'            => 'Bantul',
            'Gunung Kidul'      => 'Gunung Kidul',
            'Kulon Progo'       => 'Kulon Progo',
            'Magelang'          => 'Magelang',
            'Salatiga'          => 'Salatiga',
            'Pekalongan'        => 'Pekalongan',
            'Tegal'             => 'Tegal',
            'Brebes'            => 'Brebes',
            'Cilacap'           => 'Cilacap',
            'Purwokerto'        => 'Purwokerto',
            'Banyumas'          => 'Banyumas',
            'Purworejo'         => 'Purworejo',
            'Kebumen'           => 'Kebumen',
            'Wonosobo'          => 'Wonosobo',
            'Temanggung'        => 'Temanggung',
            'Klaten'            => 'Klaten',
            'Boyolali'          => 'Boyolali',
            'Sukoharjo'         => 'Sukoharjo',
            'Wonogiri'          => 'Wonogiri',
            'Sragen'            => 'Sragen',
            'Karanganyar'       => 'Karanganyar',
            'Demak'             => 'Demak',
            'Kudus'             => 'Kudus',
            'Jepara'            => 'Jepara',
            'Pati'              => 'Pati',
            'Rembang'           => 'Rembang',
            'Blora'             => 'Blora',
            'Grobogan'          => 'Grobogan',
            'Kendal'            => 'Kendal',
            'Batang'            => 'Batang',
            'Pemalang'          => 'Pemalang',
            'Purbalingga'       => 'Purbalingga',
            'Banjarnegara'      => 'Banjarnegara',

            // ── JAWA BARAT ──
            'Bandung'           => 'Bandung',
            'Kab. Bandung'      => 'Kab. Bandung',
            'Bekasi'            => 'Bekasi',
            'Depok'             => 'Depok',
            'Bogor'             => 'Bogor',
            'Cimahi'            => 'Cimahi',
            'Cirebon'           => 'Cirebon',
            'Tasikmalaya'       => 'Tasikmalaya',
            'Garut'             => 'Garut',
            'Sukabumi'          => 'Sukabumi',
            'Cianjur'           => 'Cianjur',
            'Subang'            => 'Subang',
            'Purwakarta'        => 'Purwakarta',
            'Karawang'          => 'Karawang',
            'Indramayu'         => 'Indramayu',
            'Majalengka'        => 'Majalengka',
            'Kuningan'          => 'Kuningan',
            'Sumedang'          => 'Sumedang',
            'Ciamis'            => 'Ciamis',
            'Pangandaran'       => 'Pangandaran',
            'Banjar'            => 'Banjar',

            // ── BANTEN ──
            'Tangerang'         => 'Tangerang',
            'Tangerang Selatan' => 'Tangerang Selatan',
            'Serang'            => 'Serang',
            'Cilegon'           => 'Cilegon',
            'Lebak'             => 'Lebak',
            'Pandeglang'        => 'Pandeglang',

            // ── DKI JAKARTA ──
            'Jakarta Pusat'     => 'Jakarta Pusat',
            'Jakarta Selatan'   => 'Jakarta Selatan',
            'Jakarta Utara'     => 'Jakarta Utara',
            'Jakarta Barat'     => 'Jakarta Barat',
            'Jakarta Timur'     => 'Jakarta Timur',

            // ── LUAR JAWA (KOTA BESAR) ──
            'Medan'             => 'Medan',
            'Palembang'         => 'Palembang',
            'Pekanbaru'         => 'Pekanbaru',
            'Batam'             => 'Batam',
            'Padang'            => 'Padang',
            'Jambi'             => 'Jambi',
            'Bandar Lampung'    => 'Bandar Lampung',
            'Bengkulu'          => 'Bengkulu',
            'Banda Aceh'        => 'Banda Aceh',
            'Pontianak'         => 'Pontianak',
            'Samarinda'         => 'Samarinda',
            'Balikpapan'        => 'Balikpapan',
            'Banjarmasin'       => 'Banjarmasin',
            'Palangkaraya'      => 'Palangkaraya',
            'Makassar'          => 'Makassar',
            'Manado'            => 'Manado',
            'Palu'              => 'Palu',
            'Kendari'           => 'Kendari',
            'Gorontalo'         => 'Gorontalo',
            'Denpasar'          => 'Denpasar',
            'Mataram'           => 'Mataram',
            'Kupang'            => 'Kupang',
            'Ambon'             => 'Ambon',
            'Ternate'           => 'Ternate',
            'Jayapura'          => 'Jayapura',
            'Sorong'            => 'Sorong',
            'Manokwari'         => 'Manokwari',
        ];
    }
}
